### PR TITLE
dont mangle timestamp on stats

### LINKED ISSUE #87: undefined in getstats
```
               "undefined" : "2016-06-03T20:45:52.297Z",
```

This oddly looks as if the timestamp is set wrong

### PR DESCRIPTION
**Pull request by fippo**
fixes #87

### CODE REVIEW

File: getstats-mangle.js [hunk 1]
```diff
@@ -13,6 +13,7 @@ module.exports = function(stats) {
   // taken from https://github.com/fippo/adapter/tree/getstats-mangling
   const standardReport = {};
   Object.keys(stats).forEach(id => {
+    if (id === 'timestamp') return;
```
Comment (ggarber) [inline getstats-mangle.js]: i see braces in single line ifs in other places of the file.   It looks to me like the most common convention
